export  const ProductsDetail = [
    {
      id: 1,
      title: "Leggings bottom",
      priceRange: "₹469 - ₹568",
      image: "/img/cards/prod1.png",
      isFavorite: false,
      sold: 34454,
    },
    {
      id: 2,
      title: "T-Shirts",
      priceRange: "₹469 - ₹568",
      image: "/img/cards/prod2.png",
      isFavorite: false,
      sold: 34454,
    },
    {
      id: 3,
      title: "Jeans",
      priceRange: "₹469 - ₹568",
      image: "/img/cards/prod3.png",
      isFavorite: false,
      sold: 34454,
    },
    {
      id: 4,
      title: "Trousers",
      priceRange: "₹469 - ₹568",
      image: "/img/cards/prod4.png",
      isFavorite: false,
      sold: 34454,
    },
    {
      id: 5,
      title: "Jeans",
      priceRange: "₹469 - ₹568",
      image: "/img/cards/prod3.png",
      isFavorite: false,
      sold: 34454,
    },
    {
        id: 4,
        title: "Trousers",
        priceRange: "₹469 - ₹568",
        image: "/img/cards/prod4.png",
        isFavorite: false,
        sold: 34454,
      },
      {
        id: 5,
        title: "Jeans",
        priceRange: "₹469 - ₹568",
        image: "/img/cards/prod3.png",
        isFavorite: false,
        sold: 34454,
      },
  ];